modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="zoesteria" #mandatory
version="1.0.0" #mandatory
displayName="Zoesteria 2" #mandatory
description='''
Mod that makes new biomes go brrrr
'''