modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="zoesteria" #mandatory
version="1.0.0" #mandatory
displayName="Zoesteria 2" #mandatory
description='''
Data driven biomes mod
'''